export const UsersMicroserviceConstants = {
  USERNAME_MIN_LENGTH: 1,
  USERNAME_MAX_LENGTH: 15,
  PASSWORD_MIN_LENGTH: 6,
  PASSWORD_MAX_LENGTH: 12,
  DESCRIPTION_MIN_LENGTH: 10,
  DESCRIPTION_MAX_LENGTH: 140,
};
