version: '3.5'
services:
  mongodb:
    image: mongo
    restart: always
    container_name: fitfriends-cabinet-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: test
      MONGO_INITDB_DATABASE: fitfriends-cabinet
    ports:
      - 15003:27017
    healthcheck:
      test: ["CMD-SHELL", "mongosh --eval \"db.adminCommand('ping')\" "]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    # volumes:
    #   - ./db:/data/db

  mongodb-express:
    image: mongo-express
    restart: always
    container_name: fitfriends-cabinet-db-express
    ports:
      - 23003:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: test
      ME_CONFIG_MONGODB_URL: mongodb://admin:test@mongodb:27017/

