export const TrainingsMicroserviceConstant = {
  TRAINING_NAME_MIN_LENGTH: 1,
  TRAINING_NAME_MAX_LENGTH: 15,
  TRAINING_PRICE_MIN_COUNT: 0,
  TRAINING_CALORIES_MIN_COUNT: 1000,
  TRAINING_CALORIES_MAX_COUNT: 5000,
  TRAINING_DESCRIPTION_MIN_LENGTH: 10,
  TRAINING_DESCRIPTION_MAX_LENGTH: 140,
  TRAINING_RATING_MIN_COUNT: 0,
  TRAINING_RATING_MAX_COUNT: 5,
  TRAINING_RATING_DEFAULT_COUNT: 0,
} as const;
